# Generated by Django 3.1.2 on 2021-02-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdrProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('msisdn', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('gt', models.CharField(max_length=200, null=True)),
                ('networkid', models.CharField(max_length=200, null=True)),
                ('system', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
