# Generated by Django 3.1.2 on 2021-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esmedlr',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
