# Generated by Django 3.1.2 on 2021-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_esmedlr_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='esmedlr',
            name='messageid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
