# Generated by Django 3.1.2 on 2021-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_esmedlr_messageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdrProcessNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('msisdn', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('gt', models.CharField(max_length=200, null=True)),
                ('networkid', models.CharField(max_length=200, null=True)),
                ('system', models.CharField(max_length=200, null=True)),
                ('msc', models.CharField(max_length=200, null=True)),
                ('imsi', models.CharField(max_length=200, null=True)),
                ('error_msg', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sendSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemId', models.CharField(max_length=200, null=True)),
                ('passwd', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
