# Generated by Django 3.1.2 on 2021-03-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrprocess',
            name='error_msg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cdrprocess',
            name='imsi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cdrprocess',
            name='msc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
